(global-set-key (kbd "C-c C-.") 'mc/edit-lines)
(global-set-key (kbd "C->")     'mc/mark-next-like-this)
(global-set-key (kbd "C-<")     'mc/mark-previous-like-this)
(global-set-key (kbd "C-s-.")   'mc/mark-all-like-this)
(global-set-key (kbd "s-SPC")   'set-rectangular-region-anchor)
